### ISSUE TITLE
[Critical] Broken in 5.X+

### ISSUE THREAD

**Issue by OdinVex** [Cultrarius/UE4_MagicConsole#11]
Broken for 5.1, complains of a header file not being found.

`./ConsoleEnhanced/Source/ConsoleEnhanced/Private/SOutputLog.cpp:16:10: fatal error: 'Classes/EditorStyleSettings.h' file not found`

I removed that because it doesn't belong in the `cpp` to begin with and simply corrected `SOutputLog.h` to include `#include "Settings/EditorStyleSettings.h"`, it now sees the header correctly.

Edit: Side note, you have a ton of deprecated calls (21). You require a small bit of rewriting, as these calls were deprecated in 5.0.

Edit: Compilation will also be faster if you don't use monolithic headers such as `EditorStyle.h` or `SlateBasics.h`:

To handle this, I removed `SlateBasics.h` and added the following to `SOutputLog.h`:

`#include "Widgets/Input/SMultiLineEditableTextBox.h"`
`#include "Framework/Text/SlateHyperlinkRun.h"`
`#include "Framework/Text/SlateTextRun.h"`
`#include "Misc/OutputDeviceHelper.h"`
`#include "SlateOptMacros.h" // To handle XXX_SLATE_FUNCTION_BUILD_OPTIMIZATION blocks`

Edit: Also corrected `#include "AssetRegistryModule.h"` to `#include "AssetRegistry/AssetRegistryModule.h"`

Edit: `LogTimestampMode` no longer exists under `UEditorStyleSettings`, at least in a quick grep of source code. It has seen some work in 5.1. I added `OutputLog` to the list of `PrivateDependencyModuleNames` and `OutputLogSettings.h` to the list of includes in `SOutputLog.h` as well as changing `UEditorStyleSettings` to `UOutputLogSettings`. It compiles, I've untested it all.

**Comment by OdinVex** [comment]
I'll probably clone, do a pull-request with all changes necessary.

**Comment by SeanDavidS** [comment]
@OdinVex Did you manage to fix it so it could be run in 5.1? The code for this would be very appreciated!

**Comment by OdinVex** [comment]
> @OdinVex Did you manage to fix it so it could be run in 5.1? The code for this would be very appreciated!

I did, but I'll need to find it if it wasn't lost in a RAID volume failure. I've been doing a lot of OS migration away from ancient *bian/*buntu and their derivatives to Arch-like distros. Keep in mind though that my edit is specific for Linux users to fix a crash.

**Comment by SeanDavidS** [comment]
> I did, but I'll need to find it if it wasn't lost in a RAID volume failure. I've been doing a lot of OS migration away from ancient *bian/*buntu and their derivatives to Arch-like distros. Keep in mind though that my edit is specific for Linux users to fix a crash.

I didn't see this as a specific fix for Linux users. So no need to dig to find it :) Thanks for your code anyway, I almost got it working on Windows with 5.1.1.

**Comment by OdinVex** [comment]
> > I did, but I'll need to find it if it wasn't lost in a RAID volume failure. I've been doing a lot of OS migration away from ancient *bian/*buntu and their derivatives to Arch-like distros. Keep in mind though that my edit is specific for Linux users to fix a crash.
> 
> I didn't see this as a specific fix for Linux users. So no need to dig to find it :) Thanks for your code anyway, I almost got it working on Windows with 5.1.1.

~~Found an old archive of what I got working on 5.1, updated it to 5.3. Maintaining a fork with those changes at https://github.com/OdinVex/ConsoleEnhanced (though I may need to be reminded when an update has occurred). Untested on Windows, *should* work, but I'm debugging a ton of other plugins, too. If you get issues, feel free to open up an Issue. It compiles, at least.~~

Edit: UE5 has a color-coded console, retired and removed fork (bugs me leaving old code up).

**Comment by patcorwin** [comment]
I know this is a very old thread but @OdinVex do you still have the fork?  It would be a huge quality of life upgrade!

**Comment by OdinVex** [comment]
> I know this is a very old thread but [@OdinVex](https://github.com/OdinVex) do you still have the fork? It would be a huge quality of life upgrade!

Unfortunately not. When UE5 rolled out the color-coded console I no longer had a need to use MagicConsole.
